name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: |
             curl -L \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer 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"\
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/198684x/test_repo/collaborators/198684x/permission
